export const ROOT = '/'
export const HOME = '/home'
export const INFO = '/about'
export const WELL = '/wellness'
export const SERV = '/services'
export const SOLO = '/services_individual'
export const CORP = '/services_corporate'